### ISSUE TITLE
OSC over TCP - disconnecting throws liblo error 9913

### ISSUE THREAD

**Issue by bennigraf** [gaborpapp/Cinder-Osc#1]
Hi there!

I try to use OSC over TCP and since the other OSC block doesn't provide this functionality, I was happy to find yours :-).

It basically works – I can connect with tcp and send OSC packets. But when **closing** the tcp connection my app crashes. (I also tried changing your sample listener to use PROTO_TCP with the same results.)

Apparently `Server::errorHandler` (OscServer.cpp:60) is called with error number 9913 (LO_ETERM, which means "string not terminated"). And inside this function I get an **EXC_BAD_ACCESS** because the variable `path` seems to be not set/pointing nowhere (`msg` is "Invalid message path", btw).

A rude fix is changing line 62 in OscServer.cpp to `ci::app::console() << "liblo server error " << num << ": " << msg << endl;`. Then I obviously still get the error ("liblo server error 9913: Invalid message path") but at least the app doesn't crash. 

(I don't know if that's a problem of your block or if liblo calls that error callback wrong... I tried digging into both sources but couldn't find where exactly errorHandler is called (and why) in the first place. Maybe you can figure it out ;-) )

Anyways, I can live with the workaround for now but still wanted to let you know!

Best,
Benni.

**Comment by gaborpapp** [comment]
Thanks for reporting this. The documentation does not state that the error handler can receive a NULL path, but checking the liblo source shows that it does happen.
