### ISSUE TITLE
Starting listener on port already in use crashes app

### ISSUE THREAD

**Issue by bennigraf** [gaborpapp/Cinder-Osc#2]
Hi again :-)

When starting a listener with Server::create() and a port that's already in use, the app crashes in OscServer.cpp:41 (`lo_server_thread_start( mThread );`). The error handler is being called and prints `liblo server error [9904]: cannot find free port`. (This is for both TCP and UDP btw.)

It seems that after failing to start a threaded server with `lo_server_thread_new_with_proto`, liblo frees both the server and the thread. `lo_server_thread_start( mThread );` throws a **BAD_ACCESS** because mThread is already gone at this point.

Could that be caught in some way using the error handler? My application might run multiple times on the same host, I'd like to just choose the next free port if the preset one is taken (until it finds a free one...)

A quick and dirty fix would be 
`if(mThread) {
        lo_server_thread_start( mThread );
    }`
and check for mThread in something like Server::isConnected(), but that seems a little hacky to me (especially since there already even is an errorHandler...). If you'd be okay with it though, I'd do it that way and create a pull request.

Best,
Benni.

**Comment by gaborpapp** [comment]
I think the proper solution would be to throw an exception from the constructor that your app could handle . Catching it in the error handler would be too late.

**Comment by bennigraf** [comment]
Hmmm

```
if(!mThread) {
        throw 0;
}
```

would work for me :-). But do you have any suggestions on _what_ to throw? I don't know if there are any conventions on this... (Also testing `!mThread` doesn't feel very good as well ;-). Sorry, I'm not really a day-to-day-C++-guy...)

**Comment by gaborpapp** [comment]
81b0c0c3 should address this.

You can catch if from your app in a loop with something like:

``` c++
try
{
    mListener = mndl::osc::Server::create( portNum );
}
catch ( const mndl::osc::OscException &exc )
{
    portNum++;
}
```

**Comment by bennigraf** [comment]
Thanks a lot for your quick fix!
Best,
Benni.
